apiVersion: v1
baseDomain: mj.co.kr
metadata:
  name: growin

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"bastion.growin.mj.co.kr:5000":{"auth":"YWRtaW46YWRtaW4="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsbt2LpEaasXEDjNzVsMqCydX3TDyW8h+uJS89TC31sLkQq+ApY4Nk9iSEy0E8JWzVlr4tpMdsh3as2xK+MRTXwHNT1/eIxiFIU3gaJRElf+v3+DCe1hzc116hU0m6QZYJJTchBzUXFGwTi2VfPOap8StxHyeq/oAynXDKzIQbxtO+Rc0Ka78jTqa2X9vSM5S0DTvdVxFUHiM41niSdBcpai8+fef44W8XrhQVBsh99E2mO/zb+gSah2JK1GkXLwTdFhGjsiGSUAi0Q5PX8C2TIFnptI0Rygj3RYp/fb6X1zXv+a3gJX9AivxqdDb400bi23OnnMQ7kbSpaRzczFN2/8/N60ayY/e8MYcQQLTPycQ0dS9vOdLI4jYsVl12xypSkMqjxV/HR2vkqvZieeQRoOsRVhL9W4QZZqtLfmUPXiphuLeTeNF9rAT/QObq7odJ+w6JE/9L9botivGb8d7nknypRL08+t9p4DLoIG8STtOdbipkqBc673jnkAnV3G0= root@bastion.growin.mj.co.kr'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGBzCCA++gAwIBAgIUBH1ZGuQKWfqp8Y71jZlGL8q+FNkwDQYJKoZIhvcNAQEL
  BQAwgZExCzAJBgNVBAYTAktSMQ4wDAYDVQQIDAVTZW91bDENMAsGA1UEBwwEQ2l0
  eTERMA8GA1UECgwIU2VsZlNpZ24xDjAMBgNVBAsMBUNsb3VkMSAwHgYDVQQDDBdi
  YXN0aW9uLmdyb3dpbi5tai5jby5rcjEeMBwGCSqGSIb3DQEJARYPbWpAZ3Jvd2lu
  LmNvLmtyMCAXDTIxMDMxNzAxMzg1OVoYDzIxMjEwMjIxMDEzODU5WjCBkTELMAkG
  A1UEBhMCS1IxDjAMBgNVBAgMBVNlb3VsMQ0wCwYDVQQHDARDaXR5MREwDwYDVQQK
  DAhTZWxmU2lnbjEOMAwGA1UECwwFQ2xvdWQxIDAeBgNVBAMMF2Jhc3Rpb24uZ3Jv
  d2luLm1qLmNvLmtyMR4wHAYJKoZIhvcNAQkBFg9takBncm93aW4uY28ua3IwggIi
  MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDtO/hCwS2na5Hkj2qLXG87hwZU
  mXvGRW1lkRwtRdYjiWi+OmsPKI4PwcbFoN9cSpoyvevOQ3FW+x1JUeFB+CKyneNT
  ZJpIKYuKq5VFrgoNICmtxXGM5abNAg2wl9zDszsXtnYvgNuPYstnCdinZfJci6wA
  EzVQrimsQQFuSz/OnVhRWio0DPdN6iTpsVBIumMD52o+dJd69s2+eUcLCdF6WJSX
  cJITna2k29/IiLIEHs61UrPCZpNtN6CtVwudBt/UBQ70hQPDcCBIwZzBdfFxWvT+
  k0l0rUBOOgIO1KiUyT3BpSPwyxU/1Rw2qD8+2WSDt97ee33So3e6YipCLuvjwdl/
  V2OTd3PTM1ubCEjs/dyG+clBk41mOJ5i218NCM22wc/eadGYypcZH05ULPPkSwsX
  71tIdB7BgUuSfgs/gRrrj86p2YG7OSJwU6gnplO/hZ5mVrD1SwW6SjD1AdtlP2RX
  J/ksDYQ4uq+WF2JXO276dfF2xlFD5X2h8y7G4ZDiBD+Tm74mkZDkVAZy+DZ2fkAq
  96f6CLtPh/lMfvVp8ej9Jome69MfnCnvn0EdfIXSY+K7YJyVu86tJ8uKa9npFiX2
  jYx+yAY7qEjjkpZSRDN8WxGlqVohQollOwTXxionhp3aShjEPS+4+O55b8MyawBM
  wHNSlXfmTV8YOJ2s6wIDAQABo1MwUTAdBgNVHQ4EFgQUlx5Z5BncyhFO6A1crQ+T
  cpeCEAIwHwYDVR0jBBgwFoAUlx5Z5BncyhFO6A1crQ+TcpeCEAIwDwYDVR0TAQH/
  BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAv3fyd1vjZJTciLwsrJmp/dOgkbFh
  dMudweYGtKwg10rIMtw0d2eiq+cpboBr3lmiMFI6AnmwJ1HvD8J1oRKz7iZ9ho7b
  /ixfRNw9kPau5rBnmrI7ji1y+xCs7jdWn8wYbnljXNgobz3j+jSynzFZNh11krlj
  mi49qhXbQIdohimCaM5MmrD+mVhACo6Slb6kM4j/OexxEYo+9mGZtyJy+V3y2xyv
  O79qYyCRhECSDiBwUdiiNQ2vPM3WUyFXkS0rTC74Jn+a8TAnX//NSC8LUHQKG04Z
  Xbyv1f3hR1zthH2Oc4lsk2fCW3AOSBxtv3TnSDxnB+I9UFuDL6qmYEf7gdTukDyx
  BgAeciS17aek/s17ktAyuuz8g9OJnYLsIRSmKcvKbk1QKS0zqx2PPUIj+piYCUQx
  /G4MJwDHtRgdaymWRJ9nxe8vtEbMD5/kH7sZf9jaLpq3usWjfSDd8dv9shN2I+bx
  RtMigt8bcUBoVxvh2sW+rOlizYchkZsxJ61PfcnYoZGOOATE8e3NmubFdefewkCF
  nRQ+f04ROR85/Mbywyang9Lsd7tQzdEOGMJseRk++9F1glHbTnnlX588B9rLORHx
  OQ0gSJ0wXdsLTOFlndmX1C9nzVgpyTtaEIvBtsfHo8EVkhcT7Jx/HsptFsTjc8nZ
  Ia6ew9x/Li9iAww=
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - bastion.growin.mj.co.kr:5000/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - bastion.growin.mj.co.kr:5000/openshift/okd
  source: quay.io/openshift/okd-content
